title: Hanna Lee # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science Intern at Oportun
  <br><br>
  Email: hannastlee@gmail.com
  <br><br>
  <a href="https://www.linkedin.com/in/hannaleest/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
